spring:
  application:
    name: hospital-web-service
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:todo_db}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
#    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:todo_db}
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
#  port: 5000

jwt:
  signing:
    key:
      secret: mySecret
  token:
    expiration:
      in:
        seconds: 604800
  http:
    request:
      header: Authorization
