spring:
  application:
    name: hospital-web-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:hospital_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        security: DEBUG

server:
  port: 8080

jwt:
  signing:
    key:
      secret: mySecret
  token:
    expiration:
      in:
        seconds: 604800
  http:
    request:
      header: Authorization

# MISC
file:
  service:
    type: local
storage:
  directory:
    path: 'D:\\hospital-img'

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: hospital-app


