# syntax=docker/dockerfile:1

# Runtime environment here
FROM amazoncorretto:8

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

RUN ./mvnw dependency:resolve

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]